# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: https://social-science-data-editors.github.io/
title: Reference information for various topics.
author: Social Science Data Editors
version: 1.0rc2
copyright: 'Copyright &copy; 2025 Social Science Data Editors. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created from <a href="https://github.com/swcool">swcool</a>.'
logo: /assets/ssde-logo.jpeg
# authors: This should be replaced by contributor lookup - there's a Github thing to do that.
description: >- # this means to ignore newlines until "baseurl:"
  These pages contains useful information for any replication package, such as where to find Terms of Use, whether data can be distributed, etc.
baseurl: "/reference" # the subpath of your site, e.g. /blog
#url: "http://codedatastandard.org" # the base hostname & protocol for your site, e.g. http://example.com
disclaimer: Journal policies may vary.
logo: https://social-science-data-editors.github.io/assets/ssde-logo.jpeg

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  information:
    output: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    icon: github
    url: https://github.com/social-science-data-editors/

# Navigation for subsites needs to retain the Home link
navigation:
  - title: Home
    url: '#dcas'
  - title: README
    url: '#readme'
  - title: Guidance
    url: '#guidance'
  - title: Reference
    url: '/reference'
  - title: Contact
    url: '#contact'